drop database tienda;
create database tienda;
use tienda;

create table categoria(
       idcategoria integer primary key auto_increment,
       nombre varchar(50) not null unique,
       descripcion varchar(256) null,
       estado bit default(1)
);

create table articulo(
       idarticulo integer primary key,
       idcategoria integer not null,
       codigo varchar(50) null,
       nombre varchar(100) not null unique,
       precio_venta decimal(11,2) not null,
       stock integer not null,
       descripcion varchar(256) null,
       estado bit default(1),
       FOREIGN KEY (idcategoria) REFERENCES categoria(idcategoria)
);

create table persona(
       idpersona integer primary key,
       tipo_persona varchar(20) not null,
       nombre varchar(100) not null,
       tipo_documento varchar(20) null,
       num_documento varchar(20) null,
       direccion varchar(70) null,
       telefono varchar(20) null,
       email varchar(50) null
);



create table rol(
       idrol integer primary key,
       nombre varchar(30) not null,
       descripcion varchar(100) null,
       estado bit default(1)
);

create table usuario(
       idusuario integer primary key,
       idrol integer not null,
       nombre varchar(100) not null,
       tipo_documento varchar(20) null,
       num_documento varchar(20) null,
       direccion varchar(70) null,
       telefono varchar(20) null,
       email varchar(50) not null,
       passwd varbinary(12) not null,
       estado bit default(1),
       FOREIGN KEY (idrol) REFERENCES rol (idrol)
);



create table ingreso(
       idingreso integer primary key,
       idproveedor integer not null,
       idusuario integer not null,
       tipo_comprobante varchar(20) not null,
       serie_comprobante varchar(7) null,
       num_comprobante varchar (10) not null,
       fecha datetime not null,
       impuesto decimal (4,2) not null,
       total decimal (11,2) not null,
       estado varchar(20) not null,
       FOREIGN KEY (idproveedor) REFERENCES persona (idpersona),
       FOREIGN KEY (idusuario) REFERENCES usuario (idusuario)
);

create table detalle_ingreso(
       iddetalle_ingreso integer primary key,
       idingreso integer not null,
       idarticulo integer not null,
       cantidad integer not null,
       precio decimal(11,2) not null,
       FOREIGN KEY (idingreso) REFERENCES ingreso (idingreso) ON DELETE CASCADE,
       FOREIGN KEY (idarticulo) REFERENCES articulo (idarticulo)
);
create table venta(
       idventa integer primary key,
       idcliente integer not null,
       idusuario integer not null,
       tipo_comprobante varchar(20) not null,
       serie_comprobante varchar(7) null,
       num_comprobante varchar (10) not null,
       fecha_hora datetime not null,
       impuesto decimal (4,2) not null,
       total decimal (11,2) not null,
       estado varchar(20) not null,
       FOREIGN KEY (idcliente) REFERENCES persona (idpersona),
       FOREIGN KEY (idusuario) REFERENCES usuario (idusuario)
);

create table detalle_venta(
       iddetalle_venta integer primary key,
       idventa integer not null,
       idarticulo integer not null,
       cantidad integer not null,
       precio decimal(11,2) not null,
       descuento decimal(11,2) not null,
       FOREIGN KEY (idventa) REFERENCES venta (idventa) ON DELETE CASCADE,
       FOREIGN KEY (idarticulo) REFERENCES articulo (idarticulo)
);
INSERT INTO `tienda`.`categoria`
(`idcategoria`,
`nombre`,
`descripcion`,
`estado`)
VALUES
(1,
'Zapatos',
'Zapatos de distintas marcas',
1);
INSERT INTO `tienda`.`categoria`
(`idcategoria`,
`nombre`,
`descripcion`,
`estado`)
VALUES
(2,
'Ropa',
'Ropa de distintas marcas',
1);
INSERT INTO `tienda`.`categoria`
(`idcategoria`,
`nombre`,
`descripcion`,
`estado`)
VALUES
(3,
'Accesorios',
'Accesorios de distintas marcas',
1);

INSERT INTO `tienda`.`articulo`
(`idarticulo`,
`idcategoria`,
`codigo`,
`nombre`,
`precio_venta`,
`stock`,
`descripcion`,
`estado`)
VALUES
(1,
1,
'ID-01',
'Bota Confort',
699,
4,
'Bota Confort Negra',
1),
(2,
1,
'ID-02',
'Calzado Confort',
299,
8,
'Bota Confort Cafe',
1),
(3,
1,
'ID-03',
'Confort Choclo',
619,
7,
'Zapato Confort Choclo/Negro',
1),
(4,
1,
'ID-04',
'Confort Bota',
399,
7,
'Bota Confort Negro',
1),
(5,
1,
'ID-05',
'Choclo Slash',
299,
10,
'Zapato Choclo Slash',
1),
(6,
1,
'ID-06',
'Kit Fashion',
399,
10,
'Zapato Kit Fashion Blanco',
1),
(7,
1,
'ID-07',
'Tenis Urbano',
399,
12,
'Tenis Urbano Negro',
1),
(8,
1,
'ID-08',
'Kit Slash',
589,
9,
'Zapatilla kit Slash Roja o Marron',
1),
(9,
1,
'ID-09',
'Confort slosh',
399,
2,
'Confort slosh Amarillo',
1),
(10,
1,
'ID-10',
'kit Bota',
449,
1,
'kit Bota Negro o Cafe',
1),
(11,
1,
'ID-11',
'Zapatilla Paris',
799,
25,
'Zapatilla Paris Marron',
1),
(12,
1,
'ID-12',
'Heavy Bota',
999,
4,
'Heavy Bota',
1),
(13,
1,
'ID-13',
'Heavy Goodyear',
399,
6,
'Bota Heavy Goodyear Cafe Roble',
1),
(14,
1,
'ID-14',
'Heavy Keebo',
389,
15,
'Bota Heavy Keebo Marron',
1),
(15,
1,
'ID-15',
'Tenis Nike',
500,
40,
'Tenis Nike Blanco para correr',
1);

INSERT INTO `tienda`.`articulo`
(`idarticulo`,
`idcategoria`,
`codigo`,
`nombre`,
`precio_venta`,
`stock`,
`descripcion`,
`estado`)
VALUES
(16,
2,
'ID-16',
'Pants Casual',
299,
15,
'Pants Casuales Rosas',
1),
(17,
2,
'ID-17',
'Pants azul',
229,
17,
'Pants Casuales Azul',
1),
(18,
2,
'ID-18',
'Chamarra cuadros',
499,
12,
'Chamarra con cuadros rojos y negros',
1),
(19,
2,
'ID-19',
'Abrigo beige',
399,
9,
'Abrigo beige elegante',
1),
(20,
2,
'ID-20',
'Abrigo gris',
399,
11,
'Abrigo gris elegante con capucha',
1),
(21,
2,
'ID-21',
'Abrigo negro',
399,
23,
'Abrigo Negro elegante',
1),
(22,
2,
'ID-22',
'Conjunto deportivo',
399,
30,
'Conjunto deportivo Azul',
1),
(23,
2,
'ID-23',
'Playera casual',
199,
6,
'Playera casual para niña Rosa',
1),
(24,
2,
'ID-24',
'Chamarra negra',
849,
4,
'Chamarra Casual Negra',
1),
(25,
2,
'ID-25',
'Sudadera Nike',
799,
1,
'Sudadera Nike Negra casual',
1),
(26,
2,
'ID-26',
'Playera Nike',
349,
7,
'Playera Nike casual Rosa',
1),
(27,
2,
'ID-27',
'Casual Nike',
449,
3,
'Camisa para dama casual Nike Blanca',
1),
(28,
2,
'ID-28',
'Playera Puma',
199,
29,
'Playera casual Puma Blanca',
1),
(29,
2,
'ID-29',
'Top casual',
99,
5,
'Top casual blanco',
1),
(30,
2,
'ID-30',
'Top amarillo',
99,
15,
'Top casual amarillo',
1);

INSERT INTO `tienda`.`articulo`
(`idarticulo`,
`idcategoria`,
`codigo`,
`nombre`,
`precio_venta`,
`stock`,
`descripcion`,
`estado`)
VALUES
(31,
3,
'ID-31',
'Mochila Puma',
479,
6,
'Mochila Puma Negra con franja roja',
1),
(32,
3,
'ID-32',
'Cangurera Puma',
299,
4,
'Cangurera Puma Rosa',
1),
(33,
3,
'ID-33',
'Morral Adidas',
399,
6,
'Morral Adidas negro',
1),
(34,
3,
'ID-34',
'Gorra Lotto',
149,
5,
'gorra Lotto Blanca',
1),
(35,
3,
'ID-35',
'Gorra Under Armor',
249,
1,
'Gorra Under Armor Negra',
1),
(36,
3,
'ID-36',
'Mochila Puma Rosa',
599,
8,
'Mochila Puma casual Rosa ',
1),
(37,
3,
'ID-37',
'Mochila Puma Azul',
599,
9,
'Mochila Puma Azul',
1),
(38,
3,
'ID-38',
'Cangurera Converse',
289,
17,
'Cangurera Converse Rosa',
1),
(39,
3,
'ID-39',
'Gorra Converse',
399,
19,
'Gorra Converse',
1),
(40,
3,
'ID-40',
'Gorra K-Swiss',
499,
1,
'Gorra K-Swiss Negra',
1);

INSERT INTO `tienda`.`rol`
(`idrol`,
`nombre`,
`descripcion`,
`estado`)
VALUES
(1,
'Administrador',
'Administrador de base de datos',
1);
INSERT INTO `tienda`.`usuario`
(`idusuario`,
`idrol`,
`nombre`,
`tipo_documento`,
`num_documento`,
`direccion`,
`telefono`,
`email`,
`passwd`,
`estado`)
VALUES
(0,
1,
'Angel Ortiz Ruiz',
'Recibo',
'1',
'Av San juan Tlaxcala, Mexico',
'5549361523',
'angel@gmail.com',
'1234',
1);
